#!/bin/bash

set -e

[ "$HAIBOOTSTRAP" ] || HAIBOOTSTRAP=$HOME/.hai/bootstrap

[ "$#" -gt "0" ] && echo "usage: $0" && exit 1

if ! type -t fakechroot >/dev/null || [ "`fakechroot sh -c 'echo $FAKECHROOT_VERSION'`" = "2.9" ]; then
  # NOTE: fakechroot-2.9 contains a bug that makes gcc, gdb and other apps
  # crash (debian #577706). this installs a work around. ideally this will
  # get fixed upstream soon, but fakechroot isn't very actively maintained.
  mkdir -p "$HAIBOOTSTRAP"
  cd "`mktemp -d`"
  rsync -av rsync.archlinux.org::abs/i686/extra/fakechroot .
  cd fakechroot
  source PKGBUILD
  wget "${source[0]}"
  tar xf fakechroot-$pkgver.tar.gz
  srcdir=$PWD
  build
  cd $srcdir/fakechroot-$pkgver
  cp src/.libs/libfakechroot.so "$HAIBOOTSTRAP"
  sed -i 's@^PATHS=/.*@PATHS=`dirname "$0"`@' scripts/fakechroot
  sed -i 's@^export FAKECHROOT_VERSION$@#&   # bug #577706 workaround@' scripts/fakechroot
  cp scripts/fakechroot "$HAIBOOTSTRAP"
fi

if ! type -t unionfs >/dev/null; then
  mkdir -p "$HAIBOOTSTRAP"
  cd "`mktemp -d`"
  ver=`wget -O- http://podgorny.cz/moin/UnionFsFuse | grep -o 'Latest version: [^ ]*' | head -n1 | grep -o '[^ ]*$'`
  wget http://podgorny.cz/unionfs-fuse/releases/unionfs-fuse-$ver.tar.bz2
  tar xf unionfs-fuse-$ver.tar.bz2
  cd unionfs-fuse-*/
  make
  cp src/unionfs "$HAIBOOTSTRAP"
fi

if ! type -t vercmp >/dev/null; then
  mkdir -p "$HAIBOOTSTRAP"
  cd "`mktemp -d`"
  echo >vercmp.c '#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>'
  wget -O- http://projects.archlinux.org/pacman.git/plain/lib/libalpm/package.c | sed -n 's/SYMEXPORT\|ALPM_LOG_FUNC//;/^int.*vercmp/,/^}$/p' >>vercmp.c
  wget -O- http://projects.archlinux.org/pacman.git/plain/src/util/vercmp.c | sed '/^#include/d;' >>vercmp.c
  gcc -o vercmp vercmp.c
  cp vercmp "$HAIBOOTSTRAP"
fi

if ! type -t bsdtar >/dev/null; then
  # TODO install bsdtar (get all the deps, preferably create a static binary)
  echo
  echo "HAI needs bsdtar, which you don't have. bootstrap can't install bsdtar"
  echo "yet. You're on your own there. :-("
  echo
fi

