#!/usr/bin/env bash
set -e

[[ "$HAIBOOTSTRAP" ]] || HAIBOOTSTRAP=$HOME/.hai/bootstrap
mkdir -p "$HAIBOOTSTRAP"

if [[ -z $(type -t fakechroot) ]]; then
  cd $(mktemp -d)
  ver=$(wget -qO- https://github.com/fakechroot/fakechroot/downloads | grep Release | head -n1 | cut -d' ' -f11)
  wget https://github.com/downloads/fakechroot/fakechroot/fakechroot-$ver.tar.gz
  tar xf fakechroot-$ver.tar.gz
  cd fakechroot-$ver
  ./configure --prefix=/usr --libdir=/usr/lib/libfakeroot --sysconfdir=/etc
  make
  cp src/.libs/libfakechroot.so "$HAIBOOTSTRAP"
  cp scripts/fakechroot "$HAIBOOTSTRAP"
fi

if [[ -z $(type -t unionfs) ]] && [[ -z $(type -t funionfs) ]]; then
  cd $(mktemp -d)
  ver=$(wget -qO- http://podgorny.cz/moin/UnionFsFuse | grep -o 'Latest version: [^ ]*' | head -n1 | grep -o '[^ ]*$')
  wget http://podgorny.cz/unionfs-fuse/releases/unionfs-fuse-$ver.tar.xz
  tar xf unionfs-fuse-$ver.tar.xz
  cd unionfs-fuse-$ver/
  make
  cp src/unionfs "$HAIBOOTSTRAP"
fi

if [[ -z $(type -t vercmp) ]]; then
  cd $(mktemp -d)
  gcc "$HAI"/vercmp.c -o vercmp
  mv vercmp "$HAIBOOTSTRAP"
fi

if [[ -z $(type -t bsdtar) ]]; then
  # TODO: get all the deps and build static bsdtar binary
  echo
  echo "HAI needs bsdtar, which you don't have. bootstrap can't install bsdtar"
  echo "yet. You're on your own there. :-("
  echo
fi
