#!/usr/bin/env bash -e

[[ "$HAIBOOTSTRAP" ]] || HAIBOOTSTRAP=$HOME/.hai/bootstrap

if [[ -z $(type -t fakechroot) ]]; then
  mkdir -p "$HAIBOOTSTRAP"
  cd $(mktemp -d)
  ver=$(wget -qO- https://github.com/fakechroot/fakechroot/downloads | grep Release | head -n1 | cut -d' ' -f11)
  wget https://github.com/downloads/fakechroot/fakechroot/fakechroot-$ver.tar.gz
  tar xf fakechroot-$ver.tar.gz
  cd fakechroot-$ver
  ./configure --prefix=/usr --libdir=/usr/lib/libfakeroot --sysconfdir=/etc
  make
  cp src/.libs/libfakechroot.so "$HAIBOOTSTRAP"
  cp scripts/fakechroot "$HAIBOOTSTRAP"
fi

if [[ -z $(type -t unionfs) ]]; then
  mkdir -p "$HAIBOOTSTRAP"
  cd $(mktemp -d)
  ver=$(wget -qO- http://podgorny.cz/moin/UnionFsFuse | grep -o 'Latest version: [^ ]*' | head -n1 | grep -o '[^ ]*$')
  wget http://podgorny.cz/unionfs-fuse/releases/unionfs-fuse-$ver.tar.bz2
  tar xf unionfs-fuse-$ver.tar.bz2
  cd unionfs-fuse-$ver/
  make
  cp src/unionfs "$HAIBOOTSTRAP"
fi

if [[ -z $(type -t vercmp)]]; then
  # TODO: building vercmp doesn't work at all; find out why OR build own implementation in pure C/Bash
  mkdir -p "$HAIBOOTSTRAP"
  cd "`mktemp -d`"
  echo >vercmp.c '#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>'
  wget -O- http://projects.archlinux.org/pacman.git/plain/lib/libalpm/package.c | sed -n 's/SYMEXPORT\|ALPM_LOG_FUNC//;/^int.*vercmp/,/^}$/p' >>vercmp.c
  wget -O- http://projects.archlinux.org/pacman.git/plain/src/util/vercmp.c | sed '/^#include/d;' >>vercmp.c
  gcc -o vercmp vercmp.c
  cp vercmp "$HAIBOOTSTRAP"
fi

if [[ -z $(type -t bsdtar) ]]; then
  # TODO: get all the deps and build static bsdtar binary
  echo
  echo "HAI needs bsdtar, which you don't have. bootstrap can't install bsdtar"
  echo "yet. You're on your own there. :-("
  echo
fi
