#!/usr/bin/env bash 
set -e

if [[ "$#" != 0 ]] && [[ "$1" != "--" ]]; then
	echo "usage: $0 [<input-dir>] [-- <makepkg-opts>]"
	exit 1
fi

source "${HAICONFIG:-$(dirname "$0")/config}"
[[ -r "$HAI/config" ]] && source "$HAI/config"

oldpwd="$PWD"; cd "$(dirname "$0")"; haibin="$PWD"; cd "$oldpwd"

if [[ "$1" ]] && [[ "$1" == "${1#-}" ]]; then
  cd "$1"
  shift
fi
[[ "$1" == "--" ]] && shift

source ./PKGBUILD
"$haibin/hai" pacman "${depends[@]}" "${makedepends[@]}" -- makepkg -d "$@"
